name: Simulated

on:
  push:
    branches-ignore: [ "ga-ignore-*" ]
  pull_request:
    branches-ignore: [ "ga-ignore-*" ]

env:
  MIRROR_URL: 'git@github.com:EpitechPGE3-2025/G-PRO-500-NCE-5-1-professionalwork-14.git'

jobs:
  push_to_mirror:
    if: github.repository != 'EpitechGE3-2025/G-PRO-500-NCE-5-1-professionalwork-14'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}